/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoachList: typeof import('./src/components/CoachList.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutImage: typeof import('@nutui/nutui')['Image']
    NutImagePreview: typeof import('@nutui/nutui')['ImagePreview']
    NutNavbar: typeof import('@nutui/nutui')['Navbar']
    NutRate: typeof import('@nutui/nutui')['Rate']
    NutSpace: typeof import('@nutui/nutui')['Space']
    NutSwiper: typeof import('@nutui/nutui')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/Swiper.vue')['default']
    SwiperCom: typeof import('./src/components/SwiperCom.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
